import React, { useRef, useState } from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import "@fontsource/source-code-pro";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

import Editor from "@monaco-editor/react";

export default function Home() {
  // State and methods for the editor
  const editorRef = useRef(null);
  const [isEditorReady, setIsEditorReady] = useState(false);
  const [__log, setLog] = useState("Console");
  const handleEditorDidMount = (editor, monaco) => {
    editorRef.current = editor;
    setIsEditorReady(true);
  };
  const getValue = () => editorRef.current.getValue();
  let appendLog = (toLog) => {
    setLog(__log + toLog);
    // document.getElementById("console").innerHTML += toLog;
  };
  let clearLog = () => {
    setLog(Date.now().toString());
  };
  const handleEditorChange = (value, event) => {
    let sandboxContainer = document.getElementById("sandboxContainer");
    let oldSandbox = document.getElementById("sandbox");
    // Remove the sandbox DOM element and regenerate it
    sandboxContainer.removeChild(oldSandbox);
    oldSandbox = null;

    let newSandbox = document.createElement("iframe");
    newSandbox.setAttribute("id", "sandbox");
    sandboxContainer.appendChild(newSandbox);
    let sandbox = document.getElementById("sandbox");

    clearLog();
    sandbox.contentWindow.console.log = (msg) => {
      appendLog(msg);
    };
    try {
      let newScript = document
        .getElementById("sandbox")
        .contentWindow.document.createElement("script");
      newScript.innerHTML = value;
      document
        .getElementById("sandbox")
        .contentWindow.document.body.appendChild(newScript);
      // let result = document.getElementById("sandbox").contentWindow.eval(value);
    } catch (e) {
      let appendError = (e) => {
        appendLog(e.message);
      };
      appendError(e);
    }
  };

  return (
    <>
      <Head>
        <title>Daemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <h1 className="text-2xl font-bold">Daemon</h1> */}
        <div id="ide">
          <Editor
            defaultLanguage="javascript"
            defaultValue="// Write your JavaScript code below"
            onChange={handleEditorChange}
            onMount={handleEditorDidMount}
            options={{
              lineNumbers: "on",
              fontFamily: "Source Code Pro",
              fontSize: "15px",
            }}
          />
        </div>
        <div id="console">
          <pre>{__log}</pre>
        </div>
        <div id="sandboxContainer">
          <iframe id="sandbox"></iframe>
        </div>
      </main>
    </>
  );
}
